version: "3"

services:
  next-app:
    container_name: paper-generator
    build:
      context: .
      dockerfile: Dockerfile
      name: smfd/paper-generator
      args:
        ENV_VARIABLE: ${ENV_VARIABLE}
        NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    restart: always
    ports:
      - 7000:3000
      # networks:
      # - my_network

      # networks:
      # my_network:
      # external: true
